name: Waka Readme Stats

on:
  push:
    branches:
      - master
  # @see scheduled events: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  # @description 16:00 UTC is 00:00 in Beijing
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
