name: Waka Readme Stats

on:
  push:
    branches:
      - master
  # @see scheduled events: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  # @description 16:00 UTC is 00:00 in Beijing
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GT_TOKEN }}
          # SHOW_OS: True
          SHOW_PROJECTS: False
          # SHOW_EDITORS: True
          # SHOW_TIMEZONE: True
          # SHOW_COMMIT: True
          # SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: True
          SHOW_LANGUAGE_PER_REPO: False
          # SHOW_LOC_CHART: True
          # SHOW_DAYS_OF_WEEK: True
          # SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: False
          # LOCALE: en
          # COMMIT_BY_ME: False
